export const ErrorCodes = {
  // Scraping errors
  SCRAPING_FAILED: 'SCRAPING_FAILED',
  NO_CONTENT: 'NO_CONTENT',
  INVALID_URL: 'INVALID_URL',
  PARSE_ERROR: 'PARSE_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  // AI errors
  AI_NO_RESPONSE: 'AI_NO_RESPONSE',
  AI_INVALID_TWEETS: 'AI_INVALID_TWEETS',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_REGENERATION_FAILED: 'AI_REGENERATION_FAILED',

  // Twitter errors
  TWITTER_POST_FAILED: 'TWITTER_POST_FAILED',
  TWITTER_COPY_FAILED: 'TWITTER_COPY_FAILED',
  TWITTER_API_ERROR: 'TWITTER_API_ERROR',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Generic errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
